server.port=8080

# HANA datasource
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver
spring.datasource.url=jdbc:sap://6b042fee-9347-4496-87f7-7f627893a66e.hna1.prod-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=4D9E756004CE41749B19799B795C62B5
spring.datasource.username=4D9E756004CE41749B19799B795C62B5_27PHM36USRGMJVDLR1J90V9H3_RT
spring.datasource.password=!#MMWQ ~Il#!cMZ:X?mmC`|UD+,P]B4P*a3P#yKG%`-N#4a=b&8H|<]v8)q{P6WoDzo|Q4q21#{3|q9FBQau;wAR{6EE(&M1Mn(F7Z.Q(s<wB@O#.,*#shQo@( ;FkVO